[book]
title = "Zault Documentation"
authors = ["Zault Contributors"]
language = "en"
src = "src"

[build]
create-missing = false

[output.html]
default-theme = "rust"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/mattneel/zault"
edit-url-template = "https://github.com/mattneel/zault/edit/master/book/{path}"
additional-css = ["theme/shiki.css"]
additional-js = ["theme/highlight.js"]

[output.html.fold]
enable = true
level = 1

[output.html.playground]
editable = false
